development:
  dialect: postgres
  database: groceries
  user: groceries
  password: groceries
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: groceries
  user: groceries
  password: groceries
  host: 127.0.0.1

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/test-buffalo_production"}}